baseURL = "https://docs.usebeagle.io/"


title = "Beagle"

enableRobotsTXT = true

theme = ["devrel"]

enableGitInfo = true

# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-169863822-2"

# Language configuration

[languages]
[languages.en]
title = "Beagle"
description = "Beagle Documentation"
languageName ="English"
contentDir = "content/en"
version_menu = "Versions"
# Weight used for sorting.
weight = 1

[languages.en.params]
menu_new_feature_text = "[NEW]"

[[languages.en.menu.main]]
    name = "C4 Model"
    weight = 20
    url = "./c4model/en/#"

[[languages.en.menu.main]]
    name = "References"
    weight = 20
    url = "https://docs-reference.usebeagle.io/"

[languages.pt]
title = "Beagle"
description = "Documentação Beagle"
languageName ="Português"
contentDir = "content/pt"
time_format_default = "02/01/2006"
time_format_blog = "02/01/2006"
version_menu = "Versões"
edit_page = "Editar essa página"
create_page = "Criar nova página"
create_issue = "Criar docs issue"
create_beagle_issue = "Criar Beagle issue"
search_label = "Procurando por algo?"
faq_path = "/pt/faq"

[languages.pt.params]
menu_new_feature_text = "[NOVO]"

[[languages.pt.menu.main]]
    name = "C4 Model"
    weight = 20
    url = "../c4model/pt-br/#"

[[languages.pt.menu.main]]
    name = "References"
    weight = 20
    url = "https://docs-reference.usebeagle.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

# Everything below this are Site Params

[params]
copyright = "Zup IT"
privacy_policy = "https://insights.zup.com.br/politica-privacidade"
playground_url = "https://playground.usebeagle.io/#"
logoName = "icons/beagle.svg"
search_label = "Looking for something?"
faq_path = "/faq"
gtm_id="GTM-5DFG5JL"
react_current_version = "2.0.0"
angular_current_version = "2.0.0"
android_current_version = "2.0.0"
flutter_current_version = "2.0.0"
ios_current_version = "2.0.0"
backend_current_version = "2.0.0"

edit_page = "Edit this page"
create_page = "Create new page"
create_issue = "Create docs issue"
create_beagle_issue = "Create Beagle issue"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/ZupIT/docs-beagle"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/ZupIT/beagle"

github_branch = "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

[[params.versions]]

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/ZupIT/docs-beagle/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/ZupIT/docs-beagle/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "mailto:beagle@zup.com.br"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name ="Twitter"
	url = "https://twitter.com/ZupInnovation"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.developer]]
	name ="Medium"
	url = "https://medium.com/zup-it"
	icon = "fab fa-medium"
        desc = "Medium"
[[params.links.developer]]
	name ="Youtube"
	url = "https://www.youtube.com/playlist?list=PLkX9oUrQ1ev7sU5idjF-jEfJIAL-j89wZ"
	icon = "fab fa-youtube"
        desc = "Youtube"
