name: Build and Upload to AWS S3

on:
  release:
    types:
      - created

env:
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'sa-east-1'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 Sync (shared)
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read --follow-symlinks static/ s3://$AWS_S3_BUCKET/shared     

      # - name: Remove static folder
      #   run: rm -rf static

      - name: Installing Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create S3 Bucket
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 mb s3://v1-6
              
      - name: S3 Sync (latest)
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read --follow-symlinks public/ s3://$AWS_S3_BUCKET/latest

      - name: S3 Sync (version)
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read --follow-symlinks public/ s3://$AWS_S3_BUCKET/v1-6

      
