name: AWS S3 UPLOAD

on:
  release:
    types:
      - created
  pull_request:
    branches: [main]

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 upload (images)
        run: aws s3 cp --acl public-read --follow-symlinks --recursive static s3://$AWS_S3_BUCKET/shared/ --exclude "playground"

      - name: Remove static images
        run: |
          cd static && find . \! -name 'playground' -delete

      - name: Installing Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - id: version
        run: echo "::set-output name=release_tag::$(echo $GITHUB_REF | sed 's/refs\/tags\///g' )"
        shell: bash

<<<<<<< HEAD
      - name: Config Proxy
        run: sed -i "s/\${latest_version}/$VERSION/" .github/workflows/proxy/index.html
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

=======
>>>>>>> 5919395837e7c54bf5ac07161c65e284baaa7fb4
      - name: S3 upload (latest version)
        run: aws s3 cp --acl public-read --follow-symlinks --recursive public s3://$AWS_S3_BUCKET/$VERSION/
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

<<<<<<< HEAD
      - name: S3 upload (redirect to latest version)
        run: aws s3 cp --acl public-read --follow-symlinks --recursive .github/workflows/proxy/index.html s3://$AWS_S3_BUCKET
=======
      - name: Config Proxy
        run: sed -i "s/\${latest_version}/$VERSION/" .github/workflows/proxy/index.html
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}
<<<<<<< HEAD
>>>>>>> 5919395837e7c54bf5ac07161c65e284baaa7fb4
=======

      - name: S3 upload (proxy to latest)
        run: aws s3 cp --acl public-read --follow-symlinks --recursive .github/workflows/proxy/index.html s3://$AWS_S3_BUCKET
>>>>>>> a3037830cc79644d756274d5c158d39dc7ac447d
