name: Horusec Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  horusec:
    name: horusec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Running Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-rc
          horusec start -p ./ --ignore="**/**/*.md" -e true -u "https://api-horusec.zup.com.br" -G true -n "${GITHUB_REPOSITORY}_${GITHUB_REF##*/}"
