name: hugo build check

on:
  pull_request:
    branches:
      - main   
    paths-ignore: 
      - .\docs

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Build check
        run: |
              cd Settings
              hugo

      - name: Git pull
        run: git pull origin main
