name: hugo to github pages

on:
  pull_request:
    branches:
      - main  
    tags-ignore:
      - '*.*' 
    paths-ignore: 
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: Getting themes
        run: git submodule update --init --recursive --depth 1

      - name: Build
        run: hugo -D
        working-directory: Settings
              
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: 'b2335bcd514b98e1ca48b6ba3fd425109851bca0'
        with:
          source-directory: 'docs'
          destination-github-username: 'vitorbassozup'
          destination-repository-name: 'doc-test'
          commit-message: 'Automated deployment'
          target-branch: 'main'
          user-email: beaglebot@zup.com.br
