name: Prepare Release

on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]*

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - id: version
        name: Get release tag
        run: echo "::set-output name=release_tag::$(echo $GITHUB_REF | sed -E "s/refs\/tags\/(v[1-9]+\.[0-9]+)\.[0-9]+/\1/g" )"
        shell: bash

      - name: Config latest path
        working-directory: config/_default
        shell: bash
        run: sed -i -E "s/latest_path = .*/latest_path = \"\/$VERSION\"/g" config.toml
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-$VERSION"

      - name: Config Proxy
        run: sed -i "s/\${latest_version}/$VERSION/" .github/workflows/proxy/index.html
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: S3 upload (redirect to latest version)
        run: aws s3 sync --acl public-read --follow-symlinks .github/workflows/proxy s3://$AWS_S3_BUCKET