name: Prepare Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]*

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          secrets: |
            beagle/docs/aws
          parse-json: true
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - id: version
        name: Get release tag
        run: echo "::set-output name=release_tag::$(echo $GITHUB_REF | sed -E "s/refs\/tags\/(v[1-9]+\.[0-9]+)\.[0-9]+/\1/g" )"
        shell: bash

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-${{ env.VERSION }}"

      - name: Config Proxy
        run: sed -i "s/\${latest_version}/$VERSION/" .github/workflows/proxy/index.html
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: Intall Dependencies
        run: yarn

      - name: Build
        run: yarn build-playground && hugo -D --minify -b $BASE_URL/$VERSION
        env:
          BASE_URL: https://docs.usebeagle.io
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: S3 upload (redirect to latest version)
        run: aws s3 sync --acl public-read --follow-symlinks .github/workflows/proxy s3://$AWS_S3_BUCKET
        env:
          AWS_S3_BUCKET: ${{ env.BEAGLE_DOCS_AWS_AWS_DOCS_S3_BUCKET }}
