name: PRODUCTION UPLOAD

on:
  push:
    branches: [release*]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_DOCS_PROD }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_DOCS_PROD}}
          aws-region: sa-east-1
          role-to-assume: ${{secrets.AWS_PROD_ROLE_TO_ASSUME}}
          role-session-name: ProdBeagleDocsPublish
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 upload (images)
        run: aws s3 sync --acl public-read --follow-symlinks static/shared s3://${{secrets.AWS_DOCS_PROD_BUCKET_NAME}}/shared/

      - name: Remove static images
        shell: bash
        working-directory: static
        run: rm -rf shared

      - name: Installing Dependencies
        run: yarn

      - name: Get version from branch name
        id: version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash

      - name: Config version path
        working-directory: config/_default
        shell: bash
        run: sed -i -E "s/current_version = .*/current_version = \"$VERSION\"/g" config.toml
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Build
        run: yarn build-playground && hugo -D --minify -b $BASE_URL/$VERSION
        env:
          BASE_URL: https://docs.usebeagle.io
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Upload FAQ
        run: aws s3 sync --acl public-read --follow-symlinks public/faq s3://${{secrets.AWS_DOCS_PROD_BUCKET_NAME}}/faq/ --delete

      - name: Upload Portuguese FAQ
        run: aws s3 sync --acl public-read --follow-symlinks public/pt/faq s3://${{secrets.AWS_DOCS_PROD_BUCKET_NAME}}/pt/faq/ --delete
        
      - name: remove FAQ
        shell: bash
        working-directory: public
        run: rm -rf faq & rm -rf pt/faq

      - name: S3 upload
        run: aws s3 sync --acl public-read --follow-symlinks public s3://$AWS_S3_BUCKET/$VERSION/ --delete
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
          AWS_S3_BUCKET: s3://${{secrets.AWS_DOCS_PROD_BUCKET_NAME}}
