name: S3 UPLOAD

on:
  push:
    branches: [release*]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          secrets: |
            beagle/docs/aws
          parse-json: true
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true

      - name: S3 upload (images)
        run: aws s3 sync --acl public-read --follow-symlinks static/shared s3://$AWS_S3_BUCKET/shared/
        env:
          AWS_S3_BUCKET: ${{ env.BEAGLE_DOCS_AWS_AWS_DOCS_S3_BUCKET }}

      - name: Remove static images
        shell: bash
        working-directory: static
        run: rm -rf shared

      - name: Installing Dependencies
        run: yarn

      - name: Get version from branch name
        id: version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash

      - name: Config version path
        working-directory: config/_default
        shell: bash
        run: sed -i -E "s/current_version = .*/current_version = \"$VERSION\"/g" config.toml
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Build
        run: yarn build-playground && hugo -D --minify -b $BASE_URL/$VERSION
        env:
          BASE_URL: https://docs.usebeagle.io
          VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Upload FAQ
        run: aws s3 sync --acl public-read --follow-symlinks public/faq s3://$AWS_S3_BUCKET/faq/ --delete
        env:
          AWS_S3_BUCKET: ${{ env.BEAGLE_DOCS_AWS_AWS_DOCS_S3_BUCKET }}

      - name: Upload Portuguese FAQ
        run: aws s3 sync --acl public-read --follow-symlinks public/pt/faq s3://$AWS_S3_BUCKET/pt/faq/ --delete
        env:
          AWS_S3_BUCKET: ${{ env.BEAGLE_DOCS_AWS_AWS_DOCS }}

      - name: remove FAQ
        shell: bash
        working-directory: public
        run: rm -rf faq & rm -rf pt/faq

      - name: S3 upload
        run: aws s3 sync --acl public-read --follow-symlinks public s3://$AWS_S3_BUCKET/$VERSION/ --exclude="c4model/*" --delete
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
          AWS_S3_BUCKET: ${{ env.BEAGLE_DOCS_AWS_AWS_DOCS_S3_BUCKET }}
